your_name = input("your full name: ")
your_age = input("your age: ")
mother_name = input("your mother full name: ")
mother_age = input("mother age: ")
father_name = input("your father full name: ")
father_age = input("father age: ")

print(" ")
print("your full name: " + your_name + " / " + "your age: " + your_age)
print(" ")
print("mother full name: " + mother_name + " / " + "mother age: " + mother_age)
print(" ")
print("father full name: " + father_name + " / " + "father age: " + father_age)
